---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: run role
      ansible.builtin.include_role:
        name: carnivuth.labcraft.install_curiel_bot
      vars:
        curiel_bot_token: test
        curiel_bot_admin: carnivuth
