Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "storax"
  
  #fixed ssh port for staging inventory
  config.vm.network "forwarded_port", id: "ssh", host: 2223, guest: 22
  # nextcloud port forwarding
  config.vm.network "forwarded_port", id: "nextcloud", host: 8080, guest: 80
  #samba port forwarding
  config.vm.network "forwarded_port", id: "samba", host: 4450, guest: 445
  config.vm.network "forwarded_port", id: "samba", host: 1390, guest: 139
  config.vm.network "forwarded_port", id: "cockpit", host: 9090, guest: 9090

  #minecraft port
  config.vm.network "forwarded_port", id: "minecraft", host: 7878, guest: 25565
  
  #minecraft port
  config.vm.network "forwarded_port", id: "xonotic", host: 7879, guest: 26000
  
  # private network with other vms
  config.vm.network "private_network", virtualbox__intnet: "homelab-staging",ip: "192.168.0.3"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end
end
