- name: Include secrets
  ansible.builtin.include_vars:
    file: vaults/vault.yaml
    name: vault
  no_log: true

- name: Create directories
  become: true
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  loop: '{{ directories }}'

- name: Copy nginx configuration
  become: true
  ansible.builtin.template:
    src: 'nginx.conf.j2'
    dest: '{{ nginx_conf_directory }}/nginx.conf'
  #no_log: true

- name: Copy nextcloud compose file
  become: true
  ansible.builtin.template:
    src: 'nextcloud-fpm.yaml.j2'
    dest: '{{ nextcloud_install_dir }}/nextcloud.yaml'
  #no_log: true

- name: Start nextcloud container
  become: true
  ansible.builtin.command:
    cmd: 'docker-compose  -f {{ nextcloud_install_dir }}/nextcloud.yaml up -d'
