services:
  backup_3ds:
    container_name: backup_3ds
    restart: unless-stopped
    image: carnivuth/backup_3ds:v2.1.0
    networks:
      - services
    environment:
      - FTPD_3DS_ADDRESSES=${FTPD_3DS_ADDRESSES}
      - FTPD_3DS_PORTS=${FTPD_3DS_PORTS}
      - BACKUP_DIRS=/3ds/Checkpoint/saves;/roms/nds/saves
      - ENABLE_DASHBOARD=true
    volumes:
      - "/mnt/containers/backup_3ds:/var/lib/backup_3ds/backups"
    labels:

      # traefik labels
      - "traefik.enable=true"
      - "traefik.http.routers.backup_3ds.entrypoints=websecure"
      - "traefik.http.services.backup_3ds.loadbalancer.server.port=80"
      - "traefik.http.routers.backup_3ds.tls.certresolver=myresolver"
      - "traefik.http.routers.backup_3ds.rule=Host(`${HOST}`)"
      - "traefik.http.routers.backup_3ds.middlewares=authelia-basicauth@docker"

      # homepage labels
      - "homepage.group=Personal Cloud"
      - "homepage.name=backup_3ds"
      - "homepage.icon=https://raw.githubusercontent.com/carnivuth/backup_3ds/4c38c457d0864cc9551cde0a258dcc3a39ef5ef9/demo/logo.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=nintendo 3DS backup service"

networks:
  services:
    name: services
    external: true
