---
services:
  grafana-database:
    image: postgres:18.6-alpine
    container_name: grafana-database
    restart: unless-stopped
    env_file: .env
    user: "${PUID_GRAFANA}"
    networks:
      - grafana
    environment:
      - POSTGRES_DB=grafana
    volumes:
      - /mnt/data/grafana/database:/var/lib/postgresql
      - /etc/passwd:/etc/passwd:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grafana -d grafana"]
      interval: 5s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:13.2.1
    container_name: grafana
    restart: unless-stopped
    user: "${PUID_GRAFANA}"
    env_file: .env
    links:
      - grafana-database
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_DEFAULT_INSTANCE_NAME=${HOST}
      - GF_SERVER_DOMAIN=${HOST}
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=grafana-database:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_SSL_MODE=disable
    ports:
      - '3000:3000'
    networks:
      - grafana
      - monitoring
      - services
    volumes:
      - /mnt/data/grafana/data:/var/lib/grafana
      - /mnt/data/grafana/provisioning:/etc/grafana/provisioning
      - /mnt/data/grafana/dashboards:/etc/dashboards

    labels:
      # traefik labels
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.routers.grafana.rule=Host(`${HOST}`)"
      # homepage labels
      - "homepage.group=Monitoring and access control"
      - "homepage.name=Grafana"
      - "homepage.icon=grafana.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=Data visualization"
      # diun labels
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.sort_tags=semver"
      - "diun.max_tags=3"

networks:
  monitoring:
    name: monitoring
    external: true
  services:
    name: services
    external: true
  grafana:
    name: grafana
    driver: bridge
