services:
  adguard:
    restart: unless-stopped
    container_name: adguard
    image: adguard/adguardhome:latest
    networks:
      - services
    ports:
      - "53:53/udp"
      - "3000:3000"
      - "2080:80"
    volumes:
      - "/var/lib/adguard:/opt/adguardhome/work"
      - "/etc/adguard:/opt/adguardhome/conf"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - "traefik.http.routers.adguard.rule=Host(`adguard.local.carnivuth.org`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"

networks:
  services:
    name: services
    external: true
