services:
  romm:
    image: rommapp/romm:5.3.1
    container_name: romm
    networks:
      - services
      - romm
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=romm-database
      - DB_NAME=romm
      - DB_USER=romm
      - ROMM_DB_DRIVER=postgresql
      - DB_PORT=5432
      - OIDC_ENABLED=true
      - OIDC_PROVIDER=authelia
      - OIDC_REDIRECT_URI=https://${HOST}/api/oauth/openid
      - ROMM_BASE_URL=https://${HOST}
    volumes:
      - /mnt/data/romm/resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - /mnt/data/romm/redis:/redis-data # Cached data for background tasks
      - /mnt/data/romm/library:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
      - /mnt/data/romm/assets:/romm/assets # Uploaded saves, states, etc.
      - /mnt/data/romm/config:/romm/config # Path where config.yml is stored
    labels:
      # traefik labels
      - "traefik.enable=true"
      - "traefik.http.routers.romm.entrypoints=websecure"
      - "traefik.http.services.romm.loadbalancer.server.port=8080"
      - "traefik.http.routers.romm.tls.certresolver=myresolver"
      - "traefik.http.routers.romm.rule=Host(`${HOST}`)"
      # homepage labels
      - "homepage.group=Personal Cloud"
      - "homepage.name=Romm"
      - "homepage.icon=romm.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=Personal rom storage"
    depends_on:
      romm-database:
        condition: service_healthy
        restart: true

  romm-database:
    networks:
      - romm
    image: postgres:17.11-alpine3.24
    security_opt:
      - no-new-privileges:true
    container_name: romm-database
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=romm
      - POSTGRES_USER=romm
    volumes:
      - /mnt/data/romm/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "romm", "-U", "romm"]
      timeout: 45s
      interval: 10s
      retries: 10

networks:
  romm:
    name: romm
    driver: bridge
  services:
    name: services
    external: true
