services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    image: portainer/portainer-ce:latest
    ports:
      - 8086:9443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/portainer:/data"
    labels:
      - traefik.http.routers.traefik.entrypoints=http
      - "traefik.http.routers.portainer.rule=Host(`portainer.docker.localhost`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
