#SPDX-License-Identifier: MIT-0
---
# tasks file for playbooks/roles/update
- name: Run "apt-get update"
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Get package facts before upgrade
  become: true
  ansible.builtin.package_facts:

- name: Set facts before upgrade
  ansible.builtin.set_fact:
    packages_before_upgrade: "{{ ansible_facts.packages }}"

- name: Remove dependencies that are no longer required and purge their configuration files (apt distros)
  when: ansible_facts.distribution == "Debian" or ansible_facts.distribution == "Ubuntu"
  become: true
  ansible.builtin.apt:
    autoremove: true
    purge: true
  register: apt_autoremove_result

- name: Install some default packages
  become: true
  ansible.builtin.package:
    name: "{{ update_packages }}"
    state: present
  register: package_install_result

- name: Install fail2ban package
  become: true
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
  notify: Restart fail2ban
  register: fail2ban_install_result

- name: Run updates
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
  register: apt_upgrade_result

- name: Get package facts after upgrade
  become: true
  ansible.builtin.package_facts:

- name: Set facts before upgrade
  ansible.builtin.set_fact:
    packages_after_upgrade: "{{ ansible_facts.packages }}"

- name: Send update diff via telegram
  when: apt_upgrade_result.changed or package_install_result.changed or fail2ban_install_result.changed or apt_autoremove_result.changed
  community.general.telegram:
    token: "{{ vault_telegram_token }}"
    api_args:
      chat_id: "{{ vault_telegram_chat_id }}"
      parse_mode: "markdown"
      text: |
          updated packages on {{ inventory_hostname }}
      disable_web_page_preview: true
      disable_notification: false
