#SPDX-License-Identifier: MIT-0
---
# tasks file for playbooks/roles/align_services
- name: Find all docker compose files
  when: align_services_apps is not defined
  ansible.builtin.find:
    paths: "roles/align_services/files/"
    patterns: "docker-compose.yml"
    recurse: true
  register: compose_files
  delegate_to: localhost

- name: Set apps variable to all compose files when unset
  ansible.builtin.set_fact:
    align_services_apps: "{{ compose_files.files | map(attribute='path') | map('dirname') | map('basename') }}"
  when: align_services_apps is not defined

- name: Include compose file
  ansible.builtin.include_vars:
    hash_behaviour: merge
    file: "files/{{ item }}/docker-compose.yml"
  loop: "{{ align_services_apps }}"

- name: Get Services volumes
  ansible.builtin.set_fact:
    volumes: "{{ services | dict2items | json_query('[*].value.volumes') | flatten }}"

- name: Get Services users
  ansible.builtin.set_fact:
    users: "{{ services | dict2items | json_query('[*].value.container_name') }}"

- name: Create compose dir
  become: true
  ansible.builtin.file:
    path: "/usr/local/containers/{{ item }}"
    state: directory
    mode: "644"
  loop: "{{ align_services_apps }}"

- name: Copy docker compose file
  become: true
  ansible.builtin.copy:
    src: "{{ item }}/docker-compose.yml"
    dest: "/usr/local/containers/{{ item }}/docker-compose.yml"
    mode: "644"
  loop: "{{ align_services_apps }}"

- name: Create application group and save GUID
  become: true
  ansible.builtin.group:
    name: "services"
  register: group_data

- name: Create application users and save PUIDs and GUIDs
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    create_home: true
    home: /usr/local/containers/{{ item }}
    groups: ["services"]
  register: users_data
  loop: "{{ users }}"

- name: Check if volumes are bindmounted files, (docker socket, timezone, ecc..)
  become: true
  ansible.builtin.stat:
    path: "{{ item.split(':')[0] }}"
  register: volumes_stats
  loop: "{{ volumes }}"

- name: Create docker compose volume dirs
  become: true
  when: (not volumes_stats.results[index].stat.exists or volumes_stats.results[index].stat.isdir) and item is regex('^/.*')
  ansible.builtin.file:
    path: "{{ item.split(':')[0] }}"
    state: directory
    mode: "775"
    group: "services"
  loop: "{{ volumes }}"
  loop_control:
    index_var: index

- name: generate env files based on templates
  become: true
  when: "align_services_apps is contains(item)"
  ansible.builtin.template:
    dest: /usr/local/containers/{{ item }}/.env
    src: files/{{ item }}/env.j2
    mode: '600'
  vars:
    container_puid: "{{ users_data.results[index].uid }}"
    container_pgid: "{{ users_data.results[index].group }}"
    services_pgid: "{{ group_data.gid }}"
    container_host: "{{ item | regex_replace('_', '-') }}.{{ align_services_apps_domain }}"
  loop: "{{ users }}"
  loop_control:
    index_var: index

- name: Create DNS records
  community.general.cloudflare_dns:
    zone: "{{ vault_cloudflare_domain }}"
    type: "{{ align_services_dns_record_type }}"
    record: "{{ item | regex_replace('_', '-') }}.{{ align_services_apps_domain }}"
    value: "{{ align_services_dns_value }}"
    api_token: "{{ vault_cloudflare_api_token }}"
    state: present
  loop: "{{ align_services_apps }}"

- name: Add cloudflare account email in docker environment
  become: true
  ansible.builtin.lineinfile:
    path: "/usr/local/containers/traefik/.env"
    create: true
    line: "CLOUDFLARE_ACCOUNT_EMAIL={{ vault_admin_email }}"
    state: present
    mode: '600'

- name: Find template files (.j2) under etc
  ansible.builtin.find:
    paths: "roles/align_services/files/{{ item }}/etc"
    patterns: "*.j2"
    recurse: true
  register: template_files
  delegate_to: localhost
  loop: "{{ align_services_apps }}"

- name: Create config directory
  become: true
  ansible.builtin.file:
    path: "/mnt/containers/{{ item.0.item }}/etc"
    owner: "{{ item.0.item }}"
    group: "{{ item.0.item }}"
    state: directory
    mode: "0644"
  loop: "{{ template_files.results | subelements('files') }}"

- name: Deploy template files (parsed)
  become: true
  ansible.builtin.template:
    src: "{{ item.1.path }}"
    dest: "/mnt/data/{{ item.0.item }}/etc/{{ item.1.path | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{ item.0.item }}"
    group: "{{ item.0.item }}"
    mode: "0644"
  loop: "{{ template_files.results | subelements('files') }}"

- name: Find config files (non-.j2) under files/etc
  ansible.builtin.find:
    paths: "roles/align_services/files/{{ item }}/etc"
    patterns: "*"
    excludes: "*.j2"
    recurse: true
    file_type: file
  register: config_files
  loop: "{{ align_services_apps }}"
  delegate_to: localhost

- name: Create config directory
  become: true
  ansible.builtin.file:
    path: "/mnt/data/{{ item.0.item }}/etc"
    owner: "{{ item.0.item }}"
    group: "{{ item.0.item }}"
    state: directory
    mode: "0644"
  loop: "{{ config_files.results | subelements('files') }}"

- name: Deploy config files (unparsed)
  become: true
  ansible.builtin.copy:
    src: "{{ item.1.path }}"
    dest: "/mnt/data/{{ item.0.item }}/etc/{{ item.1.path | basename }}"
    owner: "{{ item.0.item }}"
    group: "{{ item.0.item }}"
    mode: "0644"
  loop: "{{ config_files.results | subelements('files') }}"

- name: Start apps
  become: true
  community.docker.docker_compose_v2:
    project_src: "/usr/local/containers/{{ item }}"
    state: present
    pull: always
  register: result
  retries: 5
  delay: 1
  loop: "{{ align_services_apps }}"

- name: Prune images
  become: true
  community.docker.docker_prune:
    images: true

- name: Send Telegram notification
  community.general.telegram:
    token: "{{ vault_telegram_token }}"
    api_args:
      chat_id: "{{ vault_telegram_chat_id }}"
      parse_mode: "markdown"
      text: |
        successfully aligned apps in `{{ inventory_hostname }}`
        {% for app in align_services_apps %}
        - [app]({{ app | regex_replace('_', '-') }}.{{ align_services_apps_domain }})
        {% endfor%}
      disable_web_page_preview: true
      disable_notification: false
