---
# dns config
external_dns_server: '192.168.1.1'
dns_domain_name: 'pokelab'
dns_server: '192.168.1.96'
dns_server_backup: '192.168.1.97'

# reverse proxy cofig
certbot_admin_email:
domain_name:

# navidrome
navidrome_data: /var/lib/navidrome/data
navidrome_collection: /var/lib/navidrome/collection

#nextcloud
nextcloud_data_dir: /var/lib/nextcloud
nextcloud_apache_port: 11111

# ntfy
ntfy_cache_dir: /var/cache/ntfy
ntfy_data_dir: /var/lib/ntfy
ntfy_conf_dir: /etc/ntfy
ntfy_web: 8001

# adguard
adguard_data_dir: /var/lib/adguard
adguard_conf_dir: /etc/adguard
adguard_web: 8081
#portainer
portainer_web: 9443

# curiel bot
curiel_bot_token:
curiel_bot_admin:
curiel_bot_data_dir: /var/lib/curiel_bot

# github sync
github_sync_healthcheck:
github_sync_account:
github_sync_data_dir: /var/lib/github_sync

apps:

  - app: adguard
    app_uid: 10006
    app_baseurl: "https://{{ domain_name }}"
    reverse_proxy: false
    app_ports:
      - "53:53/udp"
      - "3000:3000"
      - "{{ adguard_web }}:80"
    app_dirs:
      - "{{ adguard_conf_dir }}"
      - "{{ adguard_data_dir }}"

  - app: ntfy
    app_uid: 10005
    exposed_port: "{{ ntfy_web }}"
    app_baseurl: "https://{{ domain_name }}"
    reverse_proxy: true
    app_ports:
      - "{{ ntfy_web }}:80"
    app_dirs:
      - "{{ ntfy_cache_dir }}"
      - "{{ ntfy_conf_dir }}"
      - "{{ ntfy_data_dir }}"

  - app: portainer
    app_uid: 10004
    exposed_port: ""
    app_baseurl: ""
    reverse_proxy: false
    app_ports:
      - "{{ portainer_web }}:{{ portainer_web }}"
      - "8000:8000"
    app_dirs: []

  - app: github_sync
    app_uid: 10003
    app_ports: []
    exposed_port: ""
    app_baseurl: ""
    reverse_proxy: false
    app_dirs:
      - "{{ github_sync_data_dir }}"
      - "{{ github_sync_log_dir }}"

  - app: curiel_bot
    app_uid: 10002
    app_ports: []
    exposed_port: ""
    app_baseurl: ""
    reverse_proxy: false
    app_dirs:
      - "{{ curiel_bot_data_dir }}"

  - app: nextcloud
    app_uid: 10001
    exposed_port: "{{ nextcloud_apache_port }}"
    app_baseurl: ""
    reverse_proxy: true
    app_ports:
      - "8080:8080"
    app_dirs:
      - "{{ nextcloud_data_dir }}"

  - app: navidrome
    app_uid: 10000
    app_baseurl: "https://{{ domain_name }}/navidrome"
    exposed_port: 4533
    reverse_proxy: true
    app_ports:
      - "4533:4533"
    app_dirs:
      - "{{ navidrome_data }}"
      - "{{ navidrome_collection }}"
