services:
  nextcloud-database:
    container_name: nextcloud-database
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - nextcloud
    volumes:
      - nextcloud-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TZ=Europe/Rome
      - TRUSTED_PROXIES=0.0.0.0/0

  nextcloud-cache:
    container_name: nextcloud-cache
    networks:
      - nextcloud
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    networks:
      - services
      - nextcloud
    links:
      - nextcloud-database
    volumes:
      - /mnt/containers/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-database
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - REDIS_HOST=nextcloud-cache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`${HOST}`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-redirect@docker"
      - "traefik.http.middlewares.nextcloud-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-redirect.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud-redirect.redirectregex.replacement=https://$${1}/remote.php/dav"
      - "homepage.group=Cloud"
      - "homepage.name=Nextcloud"
      - "homepage.icon=nextcloud.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=Personal cloud"

volumes:
  nextcloud-database:

networks:
  services:
    name: services
    external: true
  nextcloud:
    name: nextcloud
    driver: bridge
