---
- name: Install pwmanager git support
  hosts: pwmanager
  become: true
  tasks:
    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true

    - name: Create password store directory
      ansible.builtin.file:
        path: /srv/git/password-store
        state: directory
        mode: "700"
        owner: root

    - name: Initialize git inside password store dir
      ansible.builtin.command:
        cmd: git init --bare
        chdir: /srv/git/password-store
        creates: "/srv/git/password-store/branches"
