dependencies: []
galaxy_info:
  author: carnivuth
  description: align cloudflare dns configuration with local network
  company: your company (optional)
  license: MIT
  min_ansible_version: "2.2"
  galaxy_tags: []
