services:
  navidrome:
    container_name: navidrome
    restart: unless-stopped
    image: deluan/navidrome:latest
    networks:
      - services
    ports:
      - 8085:4533
    env_file: /usr/local/navidrome/.env
    volumes:
      - "/var/lib/navidrome/backup:/backup"
      - "/var/lib/navidrome/data:/data"
      - "/var/lib/navidrome/collection:/music:ro"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - "traefik.http.routers.navidrome.rule=Host(`navidrome.local.carnivuth.org`)"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
      - homepage.group=Services
      - homepage.name=Navidrome
      - homepage.icon=navidrome.svg
      - homepage.href=http://navidrome.local.carnivuth.org
      - homepage.description=Music server
networks:
  services:
    name: services
    external: true
