test:
  hosts:
    avalug:


docker_clouds:
  hosts:
    avalug:

all:
  hosts:
    avalug:
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/default/virtualbox/private_key
      ansible_host: 127.0.0.1
      ansible_port: 2221
      align_services_dns_record_type: A
      align_services_dns_value: "{{ ansible_facts['default_ipv4']['address'] }}"
      align_services_apps_domain: "{{ ansible_host }}.{{ vault_cloudflare_domain }}"
