prod:
  hosts:
    torterra.carnivuth.org:

docker_clouds:
  hosts:
    torterra.carnivuth.org:

all:
  hosts:
    torterra.carnivuth.org:
      ansible_connection: "{{ 'local' if lookup('ansible.builtin.pipe','hostname') == 'torterra' else 'ssh' }}"
      align_permissions_data_dir: /mnt/data
      align_permissions_files:
        - path: "{{ align_permissions_data_dir }}/grafana"
          owner: grafana
          mode: '0755'
          group: services
          recursive: true
        - path: "{{ align_permissions_data_dir }}/prometheus"
          owner: prometheus
          mode: '0755'
          group: nogroup
          recursive: true
        - path: "{{ align_permissions_data_dir }}/navidrome/backup"
          owner: navidrome
          mode: '0770'
          group: services
          recursive: true
        - path: "{{ align_permissions_data_dir }}/navidrome/data"
          owner: navidrome
          mode: '0700'
          group: navidrome
          recursive: true
        - path: "{{ align_permissions_data_dir }}/navidrome/collection"
          owner: navidrome
          mode: '0770'
          group: services
          recursive: true
        - path: "{{ align_permissions_data_dir }}/grafana"
          owner: grafana
          mode: '0700'
          group: grafana
          recursive: true
        - path: "{{ align_permissions_data_dir }}/metube"
          owner: metube
          mode: '0770'
          group: services
          recursive: true
