prod:
  hosts:
    torterra.carnivuth.org:

docker_clouds:
  hosts:
    torterra.carnivuth.org:
all:
  hosts:
    torterra.carnivuth.org:
      ansible_connection: "{{ 'local' if lookup('ansible.builtin.env', 'HOSTNAME') == 'torterra' else 'ssh' }}"

