plugin: community.general.proxmox
url: '{{ (lookup("ansible.builtin.unvault", "playbooks/group_vars/all/vault.yml") | from_yaml).vault_proxmox_url }}'
user: '{{ (lookup("ansible.builtin.unvault", "playbooks/group_vars/all/vault.yml") | from_yaml).vault_proxmox_user }}'
token_id: '{{ (lookup("ansible.builtin.unvault", "playbooks/group_vars/all/vault.yml") | from_yaml).vault_proxmox_token_id }}'
token_secret: '{{ (lookup("ansible.builtin.unvault", "playbooks/group_vars/all/vault.yml") | from_yaml).vault_proxmox_token_secret }}'
want_facts: true
validate_certs: false
want_proxmox_nodes_ansible_host: true
compose:
  ansible_host: proxmox_net0.ip | default(proxmox_agent_interfaces[1].ip_addresses[0]) | ansible.utils.ipaddr('address')
  ansible_port: 22
  ansible_user: "'root'"
  ansible_ssh_private_key_file:
  address: "proxmox_net0.ip"
  allowed_ips: 10.0.8.0/24
  wireguard_addresses:
    - "'10.0.8.' ~ (proxmox_net0.ip | split('.')| last | split('/') | first) ~ '/24'"
groups:
  vms: "'qemu' in (proxmox_vm_type|list)"
  cts: "'lxc' in (proxmox_vm_type| list)"
  service_manager: "'service_manager' in (proxmox_tags_parsed|list)"
  reverse_proxy: "'reverse_proxy' in (proxmox_tags_parsed|list)"
  dns_host: "'dns' in (proxmox_tags_parsed|list)"
  pbs_host: "'pbs' in (proxmox_tags_parsed|list)"
  backup_3ds_host: "'backup_3ds' in (proxmox_tags_parsed|list)"
  vpn_host: "'vpn' in (proxmox_tags_parsed|list)"
  provisioners: "'provisioner' in (proxmox_tags_parsed|list)"
  grocy_host: "'grocy' in (proxmox_tags_parsed|list)"
  xonotic_host: "'xonotic' in (proxmox_tags_parsed|list)"
  minecraft_host: "'minecraft' in (proxmox_tags_parsed|list)"
