LDAP_server:
  hosts: 
    castleterra:
          # ldap server address 
          address: 192.168.0.2
          # ldap organization
          organization: homelab                                                                                         

          # ldap dc
          dc: homelab
          # ldap password
          pwd: '{{ ldap_pwd }}'  

LDAP_clients:
  hosts:
    castleterra:
    storax:
    hooper:
    wirenine:
    nameon:
  vars:
    #ldap server parameters
    address: 192.168.0.2
    dc: homelab
    pwd: '{{ ldap_pwd }}'  

## MACHINES WITH COCKPIT 
cockpit_hosts:
  hosts:
    storax:

## MACHINES WITH DOCKER RUNTIME SUPPORT 
docker_hosts:
  hosts:
    storax:
    hooper:
  vars:
    docker_users: 
    - vagrant
    - '{{ admin_user }}'

## MACHINES WITH PORTAINER 
portainer_dashboard_host:
  hosts: 

portainer_agent_hosts:
  hosts: 
    hooper:



# MACHINE WITH HOMER DASHBOARD
dashboard_host:
  hosts:
    hooper:

# MACHINE WITH CURIEL_BOT
curiel_bot_hosts:
  hosts:
  vars:
    curiel_bot_admin: carnivuth #telegram username of the admin

# MACHINE WITH WIREGUARD SERVICE
wireguard_host:
  hosts:
    wirenine:

# MACHINE WITH DNS SERVICE
dns_host:
  hosts:
    nameon:

## MACHINES WITH JENKINS
jenkins_host:
  hosts:
    arcible:

## MACHINES WITH JENKINS AGENT
jenkins_agent_hosts:
  hosts:
    hooper:
      name: hooper # agent name
      description: hooper  node
      executors: 2
      host: 192.168.0.7
      port: 22

# MACHINE WITH MINECRAFT SERVER
minecraft_host:
  hosts:
    hydrame:

# MACHINE WITH XONOTIC SERVER
xonotic_host:
  hosts:
    hydrame:

# PROVISION MACHINE 
ansible_host:
  hosts:
    arcible:

# NAS SERVER HOST
nas_server:
  hosts:
    storax:
      # public share folder path
      public_folder_path: /home/shares/public
      # workgroup
      samba_workgroup: homelab
      # force group parameter
      public_group: public
      # samba configuration block name
      public_folder: public
      # samba authorized users
      samba_users:
        - {username: '{{ admin_user }}',password: '{{ admin_password }}'}

# ngnix_host        
nginx_hosts:
  hosts:
    starweb:
      web_server_root: /mnt/storage/web

# youcook_host        
youcook_hosts:
  hosts:
  
all:
  hosts:

    castleterra:
        ansible_user: vagrant
        ansible_ssh_private_key_file: testing/.vagrant/machines/castleterra/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2222
        ansible_hostname: castleterra

    storax:
        ansible_user: vagrant
        ansible_ssh_private_key_file: testing/.vagrant/machines/storax/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2224
        ansible_hostname: storax

    wirenine:
        ansible_user: vagrant
        ansible_ssh_private_key_file: testing/.vagrant/machines/wirenine/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2225
        ansible_hostname: wirenine

    nameon:
        ansible_user: vagrant
        ansible_ssh_private_key_file: testing/.vagrant/machines/nameon/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2226
        ansible_hostname: nameon

    hooper:
        ansible_user: vagrant

        ansible_ssh_private_key_file: testing/.vagrant/machines/hooper/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2227
        ansible_hostname: hooper
    
    arcible:
        ansible_user: vagrant
        ansible_ssh_private_key_file: testing/.vagrant/machines/arcible/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2228
        ansible_hostname: arcible
    
    hydrame:
        ansible_user: vagrant
        ansible_ssh_private_key_file: testing/.vagrant/machines/hydrame/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2229
        ansible_hostname: hydrame
    
    palkins:
        ansible_user: vagrant
        ansible_ssh_private_key_file: testing/.vagrant/machines/palkins/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2230
        ansible_hostname: palkins

    starweb:
        ansible_user: vagrant
        ansible_ssh_private_key_file: testing/.vagrant/machines/starweb/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2231
        ansible_hostname: starweb
  vars:
    #dns server parameter
    dns_server: 192.168.0.6 
    external_dns_server: 192.168.0.1 
    dns_domain_name: pokelab
    
    #default user parameter
    admin_comment: admin user
    admin_home: /home/admin
    admin_user: admin
    admin_password: '{{ common_admin_password }}'
    

