---
services:
  console_backupper:
    container_name: console_backupper
    restart: unless-stopped
    image: carnivuth/console_backupper:4.1.1-dev.1
    networks:
      - services
    env_file: .env
    volumes:
      - "/mnt/data/console_backupper/data:/var/lib/console_backupper"
      - "/mnt/data/console_backupper/cache:/var/cache/console_backupper"
      - "/mnt/data/console_backupper/etc/config.yml:/etc/console_backupper/config.yml:ro"
    labels:

      # traefik labels
      - "traefik.enable=true"
      - "traefik.http.routers.console_backupper.entrypoints=websecure"
      - "traefik.http.services.console_backupper.loadbalancer.server.port=8080"
      - "traefik.http.routers.console_backupper.tls.certresolver=myresolver"
      - "traefik.http.routers.console_backupper.rule=Host(`${HOST}`) && !PathPrefix(`/metrics`)"
      - "traefik.http.routers.console_backupper.middlewares=authelia-basicauth@docker"
      # deny access from internet for the metrics endpoint
      - "traefik.http.routers.console_backupper-metrics.rule=Host(`${HOST}`) && PathPrefix(`/metrics`)"
      - "traefik.http.routers.console_backupper-metrics.middlewares=deny@docker"

      # homepage labels
      - "homepage.group=Personal Cloud"
      - "homepage.name=console_backupper"
      - "homepage.icon=https://raw.githubusercontent.com/carnivuth/console_backupper/4c38c457d0864cc9551cde0a258dcc3a39ef5ef9/demo/logo.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=ftp console backup service"

networks:
  services:
    name: services
    external: true
