#SPDX-License-Identifier: MIT-0
---
- name: Download vimrcfile
  become: true
  ansible.builtin.get_url:
    url: https://github.com/carnivuth/toolbox/releases/download/vimrc-v{{ enforce_policies_toolbox_vimrc_version }}/vimrc
    dest: ~/.vimrc
    mode: '644'

- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ enforce_policies_timezone }}"

- name: Configure ssh daemon
  become: true
  ansible.builtin.copy:
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
    mode: "0600"
    owner: root
  notify: Restart sshd
