---
- name: Install tools
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: true

- name: Create Xonotic user
  ansible.builtin.user:
    name: xonotic
    home: '{{ xonotic_home }}/Xonotic'
    shell: /sbin/nologin
    create_home: false

- name: Create directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: xonotic
    mode: '755'
  loop:
    - '{{ xonotic_conf_dir }}'
    - '{{ xonotic_home }}'

- name: Download xonotic
  ansible.builtin.get_url:
    url: '{{ xonotic_download_url }}'
    dest: /tmp/xonotic-0.8.6.zip
    mode: '700'

- name: Unzip folder
  ansible.builtin.unarchive:
    src: /tmp/xonotic-0.8.6.zip
    dest: '{{ xonotic_home }}'
    remote_src: true
    owner: xonotic
    group: xonotic
    creates: '{{ xonotic_home }}/Xonotic/xonotic-linux-dedicated.sh'

- name: Copy server configuration
  ansible.builtin.template:
    src: server.cfg.j2
    dest: '{{ xonotic_conf_dir }}/server.cfg'
    mode: '700'
    group: xonotic
    owner: xonotic

- name: Copy systemd unit
  ansible.builtin.template:
    src: xonotic.service.j2
    dest: /etc/systemd/system/xonotic.service
    owner: 'root'
    group: 'root'
    mode: '644'

- name: Start server
  ansible.builtin.service:
    name: xonotic.service
    enabled: true
    state: restarted
