- name: Install samba
  become: true
  ansible.builtin.apt:
    name: samba
    state: present
    update_cache: true

- name: Install avahi
  become: true
  ansible.builtin.apt:
    name: avahi-daemon
    state: present
    update_cache: true

- name: Create samba public folder
  become: true
  ansible.builtin.file:
    path: '{{ public_folder_path }}'
    state: directory
    mode: '775'

- name: Create samba public group
  become: true
  ansible.builtin.group:
    name: '{{ public_group }}'
    state: present

- name: Create samba users
  become: true
  ansible.builtin.shell:
    cmd: |
      set -e -o pipefail
      && (pdbedit --user={{ item.username }} 2>&1 > /dev/null)
      || (echo '{{ item.password }}'; echo '{{ item.password }}')
      | smbpasswd -s -a {{ item.username }}
    executable: /bin/bash
  register: samba_create_users
  changed_when: "'Added user' in samba_create_users.stdout"
  no_log: true
  loop: "{{ samba_users }}"

- name: Set samba passwords correctly
  become: true
  ansible.builtin.shell:
    cmd: |
      set -e -o pipefail
      && (smbclient -U {{ item.username }}%{{ item.password }} -L 127.0.0.1 2>&1 > /dev/null)
      || (echo '{{ item.password }}'; echo '{{ item.password }}')
      | smbpasswd {{ item.username }}
    executable: /bin/bash
  register: samba_verify_users
  changed_when: "'New SMB password' in samba_verify_users.stdout"
  no_log: true
  loop: "{{ samba_users }}"


- name: Copy samba config file
  become: true
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: Restart samba
