---
# GENERICS
# ntfy endpoint
ntfy_endpoint: "https://ntfy.carnivuth.org/homelab"

# PWMANAGER
pwmanager_pub_key: "{{ vault_pwmanager_pub_key }}"

# VPN
wireguard_unmanaged_peers:
  client:
    public_key: "{{ vault_wireguard_pub_key }}"
    allowed_ips: 10.0.8.0/24
    persistent_keepalive: 0

# BACKUPPER

# proxmox backup server password for proxmox VE access
pbs_password: "{{ vault_pbs_password }}"

# remote host where to push backups
backup_remote: "u425518.your-storagebox.de"

# remote host user
proxmox_backup_remote_username: "u425518-sub3"

# backupper folder where data are stored
backupper_data_root: /mnt/datastore/

# proxmox backup server datastores
pbs_datastores:
  - {"name":"prod-server-backup", "path":"{{ backupper_data_root }}/prod-server-backup"}

# 3ds backup job
port_3ds: 5000
address_3ds: 192.168.1.99

# PROXMOX HOST

# proxmox pools
proxmox_pools:
  - {"name": "prod", "comment":"production resources"}
  - {"name": "test", "comment":"testing resources"}

# proxmox host folder to backup and send to remote
proxmox_folders_to_backup:
  - {"name":"labcraft", "path":"/usr/local/labcraft"}

# borg passphrase for proxmox host backup
proxmox_backup_borg_passphrase: "{{ vault_proxmox_backup_borg_passphrase }}"

# proxmox backup job healthceck endpoint
proxmox_backup_healthchecks_address: '{{ vault_proxmox_backup_healthchecks_address }}'

# DNS

# dns config
external_dns_server: '192.168.1.1'
dns_public_domain_name: 'carnivuth.org'
dns_domain_name: 'carnivuth.org'
dns_server: '192.168.1.96'
dns_server_backup: '192.168.1.97'
service_manager_address: '192.168.1.94'

# reverse proxy cofig
certbot_admin_email: '{{ vault_certbot_admin_email }}'
domain_name: '{{ vault_domain_name }}'

# SERVICE_MANAGER
base_docker_compose: "files/compose"
app_home_root: "/usr/local"
app_var_root: "/var/lib"
app_conf_root: "/etc"
app_cache_root: "/var/cache"

# nextcloud
nextcloud_apache_port: 11111
nextcloud_data_dir: "{{ app_var_root }}/nextcloud"
nextcloud_apache_address: "0.0.0.0"

# adguard
adguard_data_dir: "{{ app_var_root }}/adguard"
adguard_conf_dir: "{{ app_conf_root }}/adguard"
adguard_exposed_port: 8081

# curiel bot
curiel_bot_token: "{{ vault_curiel_bot_token }}"
curiel_bot_admin: "{{ vault_curiel_bot_admin }}"
curiel_bot_data_dir: "{{ app_var_root }}/curiel_bot"

# github sync
github_sync_healthcheck: '{{ vault_github_sync_healthcheck }}'
github_sync_account: '{{ vault_github_sync_account }}'
github_sync_ntfy: '{{ vault_github_sync_ntfy }}'
github_sync_data_dir: "{{ app_var_root }}/github_sync"

# openwebui
openwebui_data_dir: "{{ app_var_root }}/openwebui"
openwebui_exposed_port: 8083

# uptime kuma
kuma_data_dir: "{{ app_var_root }}/uptime_kuma"
kuma_exposed_port: 8084

# navidrome
navidrome_data_dir: "{{ app_var_root }}/navidrome"
navidrome_data: "{{ navidrome_data_dir }}/data"
navidrome_collection: "{{ navidrome_data_dir }}/collection"
navidrome_exposed_port: 8085

# portainer
portainer_exposed_port: 8086

# ntfy
ntfy_cache_dir: "{{ app_cache_root }}/ntfy"
ntfy_data_dir: "{{ app_var_root }}/ntfy"
ntfy_conf_dir: "{{ app_conf_root }}/ntfy"
ntfy_exposed_port: 8087

apps:

  - app: uptime_kuma
    app_uid: 10009
    reverse_proxy: false
    app_ports:
      - "{{ kuma_exposed_port }}:3001"
    app_dirs:
      - "{{ kuma_data_dir }}"

  - app: openwebui
    app_uid: 10008
    app_baseurl: "https://openwebui.{{ domain_name }}"
    exposed_port: "{{ openwebui_exposed_port }}"
    reverse_proxy: true
    app_ports:
      - "{{ openwebui_exposed_port }}:8080"
    app_dirs:
      - "{{ openwebui_data_dir }}"

  #     bug for dns port already used by systemd process
  #  - app: adguard
  #    app_uid: 10006
  #    app_baseurl: "https://{{ domain_name }}"
  #    reverse_proxy: false
  #    app_ports:
  #      - "53:53/udp"
  #      - "3000:3000"
  #      - "{{ adguard_exposed_port }}:80"
  #    app_dirs:
  #      - "{{ adguard_conf_dir }}"
  #      - "{{ adguard_data_dir }}"

  - app: ntfy
    app_uid: 10005
    exposed_port: "{{ ntfy_exposed_port }}"
    app_baseurl: "https://ntfy.{{ domain_name }}"
    reverse_proxy: true
    app_ports:
      - "{{ ntfy_exposed_port }}:80"
    app_dirs:
      - "{{ ntfy_cache_dir }}"
      - "{{ ntfy_conf_dir }}"
      - "{{ ntfy_data_dir }}"

  - app: portainer
    app_uid: 10004
    reverse_proxy: false
    app_ports:
      - "{{ portainer_exposed_port }}:9443"
      - "8000:8000"
    app_dirs: []

  - app: github_sync
    app_uid: 10003
    app_ports: []
    reverse_proxy: false
    app_dirs:
      - "{{ github_sync_data_dir }}"

  - app: curiel_bot
    app_uid: 10002
    app_ports: []
    reverse_proxy: false
    app_dirs:
      - "{{ curiel_bot_data_dir }}"

  - app: nextcloud
    app_uid: 10001
    exposed_port: "{{ nextcloud_apache_port }}"
    app_baseurl: "https://nextcloud.{{ domain_name }}"
    reverse_proxy: true
    app_ports:
      - "8080:8080"
    app_dirs:
      - "{{ nextcloud_data_dir }}"

  - app: navidrome
    app_uid: 10000
    app_baseurl: "https://navidrome.{{ domain_name }}"
    exposed_port: "{{ navidrome_exposed_port }}"
    reverse_proxy: true
    app_ports:
      - "{{ navidrome_exposed_port }}:4533"
    app_dirs:
      - "{{ navidrome_data }}"
      - "{{ navidrome_collection }}"
