global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'navidrome'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["navidrome:4533"]

  - job_name: 'traefik'
    scrape_interval: 1s
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: 'jellyfin'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ["jellyfin:8096"]

  - job_name: 'authelia'
    scheme: 'http'
    static_configs:
      - targets: ['authelia:9959']

  - job_name: 'adguard'
    scrape_interval: 30s
    static_configs:
      - targets: ['adguard-exporter:9618']

  - job_name: 'nextcloud'
    scrape_interval: 90s
    static_configs:
      - targets: ['nextcloud-exporter:9205']

  - job_name: telegraf
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['telegraf:9273']

  - job_name: node-exporter
    scrape_interval: 1s
    static_configs:
      - targets: ['node_exporter:9100']
