---
services:
  radicale:
    image: tomsquest/docker-radicale:3.8.0.0
    container_name: radicale
    restart: unless-stopped
    init: true
    read_only: true
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - KILL
    pids_limit: 50
    mem_limit: 256m
    volumes:
      - /mnt/data/radicale/data:/data
      - /mnt/data/radicale/etc:/config:ro
    networks:
      - services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radicale.rule=Host(`${HOST}`)"
      - "traefik.http.routers.radicale.entrypoints=websecure"
      - "traefik.http.routers.radicale.tls.certresolver=myresolver"
      - "traefik.http.routers.radicale.middlewares=authelia@docker"
      - "traefik.http.services.radicale.loadbalancer.server.port=5232"

networks:
  services:
    name: services
    external: true
