debconf:
- question: "slapd/move_old_database"
  value: true 
  vtype: select
- question: "shared/organization"
  value: "{{ organization }}" 
  vtype: string
- question: "slapd/no_configuration" 
  value: false
  vtype: boolean
- question: "slapd/domain"
  value: "{{ dc }}" 
  vtype: string
- question: "slapd/purge_database"
  value: true
  vtype: boolean
- question: "slapd/move_old_database"
  value: true 
  vtype: boolean
- question: "slapd/slapd/invalid_config"
  value: false
  vtype: boolean
- question: "slapd/password1"
  value: "{{ pwd }}"
  vtype: password
- question: "slapd/password2"
  value: "{{ pwd }}"
  vtype: password
    