---
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v3.1.0
    volumes:
      - /mnt/data/immich/data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - services
    environment:
      - TZ=Europe/Rome
      - DB_USERNAME=immich
      - DB_DATABASE_NAME=immich
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`${HOST}`)"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=myresolver"

      - "homepage.group=Personal Cloud"
      - "homepage.name=Immich"
      - "homepage.icon=immich.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=Photo library"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v3.1.0
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich-redis
    image: docker.io/valkey/valkey:9@sha256:8e8d64b405ce18f41b8e5ee20aa4687a8ed0022d1298f2ce31cdcf3a76e09411
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich-database:
    container_name: immich-database
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    env_file: .env
    environment:
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: --data-checksums
      DB_STORAGE_TYPE: HDD
    volumes:
      - /mnt/data/immich/database:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    healthcheck:
      disable: false

networks:
  services:
    name: services
    external: true

volumes:
  model-cache:
