layout:
  Media:
    iconsOnly: true
    style: row
    columns: 2
  Cloud:
    style: row
    fullWidth: true
    columns: 1
  Monitoring:
    iconsOnly: true
    style: row
    columns: 2
  Finances:
    style: row
    columns: 1
  Passwords:
    style: row
    columns: 1
  Network:
    style: row
    columns: 1
