title: Carnivuth personal services
bookmarksStyle: icons
background:
  image: /images/background.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 90 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100
layout:
  Personal cloud:
    style: row
    fullWidth: true
    columns: 1
  Media:
    iconsOnly: true
  Monitoring and access control:
    iconsOnly: true
  Finances:
    style: row
    columns: 1
  Passwords:
    style: row
    columns: 1
  Network:
    style: row
    columns: 1
