---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: true
    - name: Stop process on port 53
      ansible.builtin.apt:
        update_cache: true
