---
services:
  keykloak:
    restart: unless-stopped
    container_name: keycloak
    command: start
    networks:
      - services
    image: quay.io/keycloak/keycloak:26.3.3
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.keycloak.rule=Host(`keycloak.local.carnivuth.org`)
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
      - traefik.http.routers.keycloak.entrypoints=websecure
      - traefik.http.routers.keycloak.tls=true
      - homepage.group=Services
      - homepage.name=Keycloak
      - homepage.icon=keycloak.svg
      - homepage.href=https://keycloak.local.carnivuth.org
      - homepage.description=Idp service

networks:
  services:
    name: services
    external: true


