- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: true

- name: Enable dns service
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    line: 'listen-address=::1,127.0.0.1,{{ dns_server }}'

- name: 'Add dns server entry in the {{ hostvars[item].ansible_host }}'
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: '{{ hostvars[item].address | regex_replace( "(.*)/.*", "\1" )}} {{ item }}.{{ dns_domain_name }} {{ item }}'
  loop: '{{ groups["all"] }}'
  ignore_errors: true

- name: Start dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
