- name: Install packages
  become: true
  ansible.builtin.apt:
    name:
      - git
      - ansible
      - python3-passlib
    state: present
    update_cache: true

- name: Clone homelab repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/carnivuth/labcraft
    dest: /usr/local/labcraft
