---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Test common role
      ansible.builtin.include_role:
        name: roles/common
      vars:
        admin_home: /home/admin
        admin_comment: admin
        admin_password: admin
        admin_user: admin
