---
- name: set dns ip address
  ansible.builtin.set_fact:
    dns_ip: '{{ address | regex_replace( "(.*)/.*", "\1" ) }}'

- name: Copy dnsmasq configuration
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name: Copy /etc/resolv.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: 'Add dns server entry in the {{ hostvars[item].ansible_host }}'
  when: hostvars[item].address is defined
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: '{{ hostvars[item].address | regex_replace( "(.*)/.*", "\1" )}} {{ item }}.{{ dns_domain_name }} {{ item }}'
  loop: '{{ groups["all"] }}'
  ignore_errors: true

- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: true

- name: Start dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
    enabled: true
