services:
  minecraft-server:
    image: itzg/minecraft-server:2025.10.1
    restart: unless-stopped
    container_name: minecraft-server
    tty: true
    stdin_open: true
    environment:
      - "EULA=TRUE"
      - "TZ=Europe/Rome"
      - "TYPE=VANILLA"
      - "DIFFICULTY=hard"
      - "SERVER_NAME=carnivuth-mc"
    volumes:
      - /mnt/containers/minecraft-server/:/data
    labels:
      # diun labels
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.sort_tags=semver"
      - "diun.max_tags=3"
      # traefik labels
      - "traefik.enable=true"
      - "traefik.tcp.routers.minecraft-server.rule=HostSNI(`${HOST}`)"
      - "traefik.tcp.routers.minecraft-server.entrypoints=minecraft"
      - "traefik.tcp.services.minecraft-server.loadbalancer.server.port=25565"
      - "traefik.tcp.routers.minecraft-server.tls=true"
networks:
  services:
    name: services
    external: true
