services:
  nextcloud-database:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    restart: always
    networks:
      - services
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-database
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.local.carnivuth.org`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

volumes:
  nextcloud:
  db:

networks:
  services:
    name: services
    external: true
