#!/bin/bash
# Redirect output to stderr.
exec 1>&2

LOG_DIR="/var/log/labcraft"; if [[ ! -d "$LOG_DIR" ]];then mkdir -p "$LOG_DIR"; fi
NTFY_ADDRESS="https://pokelab.ddns.net/ntfy/homelab"

# check if last commit contains something that has notes in the name
PB=playbooks
if git diff --name-only HEAD HEAD~1 | grep "$PB" || git diff --name-only HEAD HEAD~1 | grep "scripts" ; then
  # run ansible-playbooks
  source env/bin/activate
  ansible-playbook -i inventory/prod.proxmox.yaml -e 'vars_file=prod' playbooks/common.yml >> "$LOG_DIR/common.log"
  ansible-playbook -i inventory/prod.proxmox.yaml -e 'vars_file=prod' playbooks/configure_service_manager.yml >> "$LOG_DIR/configure_service_manager.log"
else
  echo "no $PB modified, nothing to do" >> "$LOG_DIR/general.log"
fi

# check if last commit contains something that has notes in the name
PB=terraform
if git diff --name-only HEAD HEAD~1 | grep "$PB" || git diff --name-only HEAD HEAD~1 | grep "scripts" ; then

  # run terraform
  cd terraform
  timestamp="$(date +%s)"
  terraform plan -out "$LOG_DIR/terraform.$timestamp.plan.log" && terraform apply -auto-approve "$LOG_DIR/terraform.$timestamp.plan.log"

  # sleep to ensure ntfy container is up
  sleep 2
  curl "$NTFY_ADDRESS" -d "labcraft terraform run $timestamp ended"
else
  echo "no $PB modified, nothing to do" >> "$LOG_DIR/general.log"
fi
