services:
  crafty-controller:
    container_name: crafty-controller
    image: registry.gitlab.com/crafty-controller/crafty-4:4.5.4
    restart: unless-stopped
    networks:
      - services
    environment:
        - TZ=Europe/Rome
    ports:
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - /mnt/containers/crafty-controller/backups:/crafty/backups
        - /mnt/containers/crafty-controller/logs:/crafty/logs
        - /mnt/containers/crafty-controller/servers:/crafty/servers
        - /mnt/containers/crafty-controller/config:/crafty/app/config
        - /mnt/containers/crafty-controller/import:/crafty/import
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crafty-controller.rule=Host(`${HOST}`)"
      - "traefik.http.services.crafty-controller.loadbalancer.server.port=8443"
      - "traefik.http.routers.crafty-controller.entrypoints=websecure"
      - "traefik.http.routers.crafty-controller.tls=true"
      - "traefik.http.routers.crafty-controller.tls.certresolver=myresolver"
      - "homepage.group=Game Servers"
      - "homepage.name=Crafty controller"
      - "homepage.icon=crafty-controller.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=Comics and books library"
networks:
  services:
    name: services
    external: true
