Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  #hostname
  config.vm.hostname = "wailhost"
  
  #port forwardings
  config.vm.network "forwarded_port", host: 9443, guest: 9943, protocol: "tcp"
  config.vm.network "forwarded_port",  host: 8000, guest: 8000, protocol: "tcp"
  config.vm.network "forwarded_port",  host: 8001, guest: 8001, protocol: "tcp"
  config.vm.network "forwarded_port",  host: 25565, guest: 25565, protocol: "tcp"
  config.vm.network "forwarded_port",  host: 9000, guest: 9000, protocol: "tcp"
  #fixed ssh port for staging inventory
  config.vm.network "forwarded_port", id: "ssh", host: 2224, guest: 22
  
  #disk size
  config.disksize.size = '50GB'
  
  #network
  config.vm.network "private_network", virtualbox__intnet: "homelab-staging",ip: "192.168.0.4"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
