---
- name: Update all packages to their latest version (apt distros)
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Update all packages to their latest version (pacman distros)
  when: ansible_distribution == "Archlinux"
  community.general.pacman:
    upgrade: true
    update_cache: true

- name: Install some default packages (pacman distros)
  when: ansible_distribution == "Archlinux"
  community.general.pacman:
    name: "{{ packages }}"
    state: present

- name: Install some default packages (apt distros)
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  ansible.builtin.apt:
    pkg: "{{ packages }}"
    state: present
    update_cache: true


- name: Configure vim
  block:
    - name: Clone vim configuration repo
      ansible.builtin.git:
        repo: "https://github.com/carnivuth/vim_cfg"
        dest: "/root/vim_cfg"
        force: true

    - name: Install vim configuration
      community.general.make:
        chdir: "/root/vim_cfg"
        target: "install"

    - name: Create fzf directory plugin
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      ansible.builtin.file:
        path: /usr/share/vim/vimfiles/plugin
        state: directory

    - name: link fzf plugin
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      ansible.builtin.file:
        src: /usr/share/doc/fzf/examples/plugin/fzf.vim
        dest: /usr/share/vim/vimfiles/plugin/fzf.vim
        state: link

- name: Copy bash_aliases
  ansible.builtin.copy:
    src: .bash_aliases
    dest: "/root/.bash_aliases"
    mode: "700"

- name: Copy bashrc
  ansible.builtin.copy:
    src: .bashrc
    dest: "/root/.bashrc"
    mode: "700"

- name: Set timezone
  community.general.timezone:
    name: "Europe/Rome"
  notify: Restart cron
