---
- name: Update all packages to their latest version (apt distros)
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Update all packages to their latest version (pacman distros)
  when: ansible_distribution == "Archlinux"
  community.general.pacman:
    upgrade: true
    update_cache: true

- name: Install some default packages (pacman distros)
  when: ansible_distribution == "Archlinux"
  community.general.pacman:
    name: "{{ packages }}"
    state: present

- name: Install some default packages (apt distros)
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true

- name: Copy bash_aliases
  ansible.builtin.copy:
    src: .bash_aliases
    dest: "/root/.bash_aliases"
    mode: "700"

- name: Copy bashrc
  ansible.builtin.copy:
    src: .bashrc
    dest: "/root/.bashrc"
    mode: "700"

- name: Install toolbox
  block:
    - name: Clone repo
      ansible.builtin.git:
        repo: "https://github.com/carnivuth/toolbox"
        dest: "/root/toolbox"
        force: true

    - name: Install deps
      ansible.builtin.command:
        cmd: /root/toolbox/configure
        chdir: /root/toolbox

    - name: Install toolbox
      community.general.make:
        chdir: "/root/toolbox"
        target: "install"

- name: Set timezone
  community.general.timezone:
    name: "Europe/Rome"
  notify: Restart cron
