- name: Update all packages to their latest version
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install some default packages
  become: true
  ansible.builtin.apt:
    pkg:
      - vim
      - sudo
    state: present

- name: Copy motd file
  become: true
  ansible.builtin.copy:
    src: '{{ ansible_hostname }}-motd'
    dest: /etc/motd
    mode: '644'
  ignore_errors: true

- name: Run create admin task
  ansible.builtin.include_tasks:
    file: create_admin_user.yaml

- name: Copy default vim configuration
  become: true
  ansible.builtin.copy:
    src: .vimrc
    dest: '{{ item.home }}/.vimrc'
    mode: '600'
    owner: '{{ item.owner }}'
  loop: '{{ users }}'

- name: Copy default bash aliases
  become: true
  ansible.builtin.copy:
    src: .bash_aliases
    dest: '{{ item.home }}/.bash_aliases'
    mode: '700'
    owner: '{{ item.owner }}'
  loop: '{{ users }}'

- name: Include bash aliases in bashrc
  become: true
  ansible.builtin.lineinfile:
    path: '{{ item.home }}/.bashrc'
    regexp: ^source ~/.bash_aliases
    line: source ~/.bash_aliases
    state: present
  loop: '{{ users }}'

- name: Export TERM variable
  become: true
  ansible.builtin.lineinfile:
    path: '{{ item.home }}/.bashrc'
    regexp: ^export TERM=linux
    line: export TERM=linux
    state: present
  loop: '{{ users }}'
