---
- name: Install nfs and configure share
  hosts: nfs
  vars:
    nfs_share: /mnt
  tasks:
    - name: Install nfs
      ansible.builtin.apt:
        name: nfs-kernel-server
        autoremove: true
        purge: true

    - name: start and enable nfs server
      ansible.builtin.service:
        name: nfs-server
        state: restarted
        enabled: true

    - name: Add sharepoint to nfs server configuration
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "{{ nfs_share }} {{ address | ansible.utils.ipaddr('network/prefix') }}(rw,sync,no_subtree_check)"
        state: present
      notify: Refresh nfs server

  handlers:

    - name: Refresh nfs server
      ansible.builtin.command:
        cmd: "exportfs -arv"
