- name: Configure proxmox pools
  hosts: pve
  vars:

    # pools to create in the proxmox host
    proxmox_pools:
      - {"name": "prod", "comment":"production resources"}
      - {"name": "test", "comment":"testing resources"}

  tasks:

    - name: Create pool {{ item.name }}
      community.general.proxmox_pool:
        api_host: pve
        api_user: "{{ vault_proxmox_user }}"
        api_token_id: "{{ vault_proxmox_token_id }}"
        api_token_secret: "{{ vault_proxmox_token_secret }}"
        poolid: "{{ item.name }}"
        comment: "{{ item.comment }}"
      loop: "{{ proxmox_pools }}"

