#SPDX-License-Identifier: MIT-0
---
# tasks file for playbooks/roles/align_permissions
- name: Set permissions for files and directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: "{{ item.recursive }}"
  loop: "{{ align_permissions_files }}"
  register: align_permissions_result

- name: Send telegram notification if permissions were changed
  when: align_permissions_result.changed
  community.general.telegram:
    token: "{{ vault_telegram_token }}"
    api_args:
      chat_id: "{{ vault_telegram_chat_id }}"
      text: |
        "Permissions have been aligned on {{ inventory_hostname }}:"

        {%- for item in align_permissions_result %}
        {%- if item.changed %}
        - {{ item.item.path }}: {{ item.item.mode }} (owner: {{ item.item.owner }}, group: {{ item.item.group }})
        {%- endif %}
        {%- endfor %}
