---
driver:
  name: docker

platforms:
  - name: klefky
    image: debian:bookworm
    groups:
      - pwmanager

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
