#SPDX-License-Identifier: MIT-0
---
# tasks file for playbooks/roles/provision_grafana/
- name: Create destination dirs
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ provision_grafana_configuration_dir }}/datasources"
    - "{{ provision_grafana_configuration_dir }}/alerting"
    - "{{ provision_grafana_configuration_dir }}/dashboards"

- name:  Install datasources
  notify: Restart grafana
  become: true
  ansible.builtin.copy:
    src: "datasources.yml"
    dest: "{{ provision_grafana_configuration_dir }}/datasources/datasources.yml"
    mode: "644"
  register: datasource_result

- name: Copy dashboards
  become: true
  notify: Restart grafana
  ansible.builtin.copy:
    src: "dashboards/"
    dest: "{{ provision_grafana_dashboards_dir }}/"
    mode: "644"
  register: dashboard_result

- name: Install dashboards
  become: true
  notify: Restart grafana
  ansible.builtin.copy:
    src: "dashboards.yml"
    dest: "{{ provision_grafana_configuration_dir }}/dashboards/dashboards.yml"
    mode: "644"
  register: dashboards

#- name: Install alerting
#  notify: Restart grafana
#  ansible.builtin.copy:
#    src: "alerting.yml"
#    dest: "{{ provision_grafana_configuration_dir }}/alerting/alerting.yml"
#    mode: "644"

- name: Send Telegram notification
  when: datasource_result.changed or dashboard_result.changed or dashboards.changed
  community.general.telegram:
    token: "{{ vault_telegram_token }}"
    api_args:
      chat_id: "{{ vault_telegram_chat_id }}"
      parse_mode: "markdown"
      text: |
        Aligned grafana dashboards on `{{ inventory_hostname }}`
      disable_web_page_preview: true
      disable_notification: false
