---
- name: Copy configuration for {{ app }}
  ansible.builtin.template:
    src: "templates/reverse_proxy/{{ app }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ app }}.conf"

- name: enable configuration for {{ app }}
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ app }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ app }}.conf"
    state: link
