---
- name: Check if configuration is present
  ansible.builtin.lineinfile:
    line: "# {{ app }}"
    path: "/etc/nginx/sites-enabled/main"
  check_mode: true
  register: config

- name: Add {{ app }} reverse proxy configuration
  when: config.changed
  ansible.builtin.blockinfile:
    insertafter: 'server {'
    block: "{{ lookup('ansible.builtin.template', 'templates/reverse_proxy/' ~ app ~ '.j2') }}"
    path: "/etc/nginx/sites-enabled/main"
    marker: "# { mark } {{ app }}"
