- name: Get backupper fingerprints
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: >
      set -o pipefail &&
      ssh {{ backupper | quote }} 'proxmox-backup-manager cert info | grep Fingerprint'
      | awk -F':' '{ $1=""; print $0}' > /tmp/{{ backupper | quote }}.fingerprint
    creates: "/tmp/{{ backupper }}.fingerprint"

- name: Slurp fingerprint
  ansible.builtin.slurp:
    path: "/tmp/{{ backupper }}.fingerprint"
  register: fingerprint

- name: Add storage to proxmox
  ansible.builtin.command:
    cmd: >
      pvesm add pbs {{ backupper }}
      --server {{ backupper }}
      --datastore '{{ datastore.name }}'
      --fingerprint "{{ fingerprint.content | b64decode | trim | replace(' ',':')}}"
      --username root@pam
      --password {{ pbs_password }}
  loop: "{{ pbs_datastores }}"
  loop_control:
    loop_var: datastore
