- hosts: all
  roles:
   - common

- import_playbook:  ldap.yaml
- import_playbook:  docker.yaml
- import_playbook: portainer-agent.yaml
- import_playbook: portainer-dashboard.yaml
- import_playbook: homer.yaml
- import_playbook: samba.yaml
