---
- name: Install proxmox backup server
  hosts: backupper
  become: true
  tasks:
    - name: Install some packages
      ansible.builtin.apt:
        name:
          - ftp
          - netcat-traditional
          - curl
          - rsync
        state: present
        update_cache: true

    - name: Add proxmox backup server repo key
      ansible.builtin.get_url:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
        dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
        mode: '644'

    - name: Add proxmox backup server repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg] http://download.proxmox.com/debian/pbs bookworm pbs-no-subscription"
        filename: proxmox_backup_server
        state: present

    - name: Install pbs and update cache
      notify: Send ntfy.sh update
      ansible.builtin.apt:
        name: proxmox-backup-server
        state: present
        update_cache: true

    - name: Copy backup script
      notify: Send ntfy.sh update
      ansible.builtin.template:
        src: templates/sync_with_remote.sh.j2
        dest: /usr/local/bin/sync_with_remote.sh
        mode: '755'

    - name: Add datastore
      ansible.builtin.command:
        cmd: "proxmox-backup-manager datastore create {{ item.name }} {{ item.path }}"
        creates:
      loop: "{{ pbs_datastores }}"

    - name: Add backup sync cronjob
      notify: Send ntfy.sh update
      ansible.builtin.cron:
        name: "backup sync"
        minute: "0"
        hour: "22"
        job: "/usr/local/bin/sync_with_remote.sh > /dev/null"

    - name: Copy 3ds backup script
      ansible.builtin.template:
        src: templates/backup_3ds.sh.j2
        dest: /usr/local/bin/backup_3ds.sh
        mode: '755'

    - name: Add 3ds backup cronjob
      ansible.builtin.cron:
        name: "3ds backup"
        job: "/usr/local/bin/backup_3ds.sh >> /var/log/backup_3ds.log 2>&1"

  handlers:
    - name: Send ntfy.sh update
      ansible.builtin.uri:
        url: "{{ ntfy_endpoint }}"
        method: POST
        body: "installation of pbs instance on {{ inventory_hostname }} completed"
