- name: Align cloudflare dns
  hosts: proxmox_all_running
  vars:
    # dns pb
    cloudflare_subdomain: 'local'
  tasks:

    - name: Create a DNS record inside cloudflare
      community.general.cloudflare_dns:
        zone: "{{ vault_cloudflare_domain }}"
        type: A
        record: "{{ ansible_facts.hostname }}.{{ cloudflare_subdomain }}.{{ vault_cloudflare_domain }}"
        value: "{{ ansible_facts.default_ipv4.address }}"
        api_token: "{{ vault_cloudflare_api_token }}"
        state: present

    - name: Configure dns servers
      become: true
      ansible.builtin.copy:
        mode: '644'
        dest: /etc/resolv.conf
        content: |
          search {{ vault_cloudflare_domain }}
          nameserver {{ vault_cloudflare_primary_dns }}
          nameserver {{ vault_cloudflare_secondary_dns }}

- name: Update cloudflare public ip
  hosts: pve
  tasks:
    - name: Get public IP address
      ansible.builtin.uri:
        url: https://ifconfig.me/ip
        return_content: true
      register: public_ip

    - name: Create a DNS record inside cloudflare
      register: cloudflare_record
      community.general.cloudflare_dns:
        zone: "{{ vault_cloudflare_domain }}"
        type: A
        record: "{{ vault_cloudflare_domain }}"
        value: "{{ public_ip.content }}"
        api_token: "{{ vault_cloudflare_api_token }}"
        state: present

    - name: Send notification of the changed record via telegram api
      when: cloudflare_record.changed
      community.general.telegram:
        token: "{{ vault_telegram_token }}"
        api_args:
          chat_id: "{{ vault_telegram_chat_id }}"
          parse_mode: "markdown"
          text: "proxmox public ip has changed to `{{ public_ip.content }}` "
          disable_web_page_preview: true
          disable_notification: false
