---
- name: Run common role on all nodes
  hosts: all
  vars:
    arch_packages:
      - vim
    deb_packages:
      - vim

  tasks:
    - name: Update packages
      block:
        - name: Remove dependencies that are no longer required and purge their configuration files (apt distros)
          when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
          ansible.builtin.apt:
            autoremove: true
            purge: true

        - name: Update all packages to their latest version (apt distros)
          notify: Send ntfy.sh update
          when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
          ansible.builtin.apt:
            upgrade: true
            update_cache: true

        - name: Update all packages to their latest version (pacman distros)
          notify: Send ntfy.sh update
          when: ansible_distribution == "Archlinux"
          community.general.pacman:
            upgrade: true
            update_cache: true

        - name: Install some default packages (pacman distros)
          notify: Send ntfy.sh update
          when: ansible_distribution == "Archlinux"
          community.general.pacman:
            name: "{{ arch_packages }}"
            state: present

        - name: Install some default packages (apt distros)
          notify: Send ntfy.sh update
          when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
          ansible.builtin.apt:
            name: "{{ deb_packages }}"
            state: present
            update_cache: true
      rescue:
        - name: Send ntfy.sh notification of failed nodes
          ansible.builtin.uri:
            url: "https://pokelab.ddns.net/ntfy/homelab"
            method: POST
            body: " update failed on host {{ inventory_hostname }}"


- name: Perform some basic configurations
  hosts: all:!provisioners
  tasks:
    - name: Copy bash_aliases
      notify: Send ntfy.sh update
      ansible.builtin.copy:
        src: files/.bash_aliases
        dest: "/root/.bash_aliases"
        mode: "700"

    - name: Copy bashrc
      notify: Send ntfy.sh update
      ansible.builtin.copy:
        src: files/.bashrc
        dest: "/root/.bashrc"
        mode: "700"

  handlers:
    - name: Send ntfy.sh update
      ansible.builtin.uri:
        url: "https://pokelab.ddns.net/ntfy/homelab"
        method: POST
        body: "{{ inventory_hostname }} common playbook completed"
