---
- name: Create proxmox pools for resources
  hosts: localhost
  tasks:
    - name: Install some packages
      ansible.builtin.apt:
        name:
          - curl
          - rsync
          - borgbackup
        state: present
        update_cache: true

    - name: Create pool {{ item.name }}
      community.general.proxmox_pool:
        api_host: pve
        api_user: "{{ vault_proxmox_user }}"
        api_token_id: "{{ vault_proxmox_token_id }}"
        api_token_secret: "{{ vault_proxmox_token_secret }}"
        poolid: "{{ item.name }}"
        comment: "{{ item.comment }}"
      loop: "{{ proxmox_pools }}"

    - name: Setup backup of host
      block:
        - name: Copy backup script
          notify: Send ntfy.sh update
          ansible.builtin.template:
            src: templates/backup_host.sh.j2
            dest: /usr/local/bin/backup_host.sh
            mode: '700'

        - name: Copy ssh config
          notify: Send ntfy.sh update
          ansible.builtin.template:
            src: templates/proxmox_ssh_config.j2
            dest: /root/.ssh/config
            mode: '700'

        - name: Add backup sync cronjob
          notify: Send ntfy.sh update
          ansible.builtin.cron:
            name: "backup sync"
            minute: "0"
            hour: "22"
            job: "/usr/local/bin/backup_host.sh > /dev/null"

  handlers:
    - name: Send ntfy.sh update
      ansible.builtin.uri:
        url: "{{ ntfy_endpoint }}"
        method: POST
        body: "configuration of proxmox host {{ inventory_hostname }} completed"
