---
- name: Install proxmox backup server
  hosts: backup_3ds_host
  become: true
  tasks:
    - name: Install some packages
      ansible.builtin.apt:
        name:
          - ftp
          - netcat-traditional
        state: present
        update_cache: true

    - name: Copy 3ds backup script
      ansible.builtin.template:
        src: templates/backup_3ds.sh.j2
        dest: /usr/local/bin/backup_3ds.sh
        mode: '755'

    - name: Add 3ds backup cronjob
      ansible.builtin.cron:
        name: "3ds backup"
        job: "/usr/local/bin/backup_3ds.sh >> /var/log/backup_3ds.log 2>&1"
