---
- name: Configure reverse proxy to expose service manager applications
  become: true
  hosts: reverse_proxy
  tasks:
    - name: Install reverse proxy for {{ apps[element].app }}
      when: apps[element].reverse_proxy is true
      ansible.builtin.include_tasks:
        file: add_nginx_reverse_proxy.yml
      vars:
        app: "{{ apps[element].app }}"
        exposed_port: "{{ apps[element].exposed_port }}"
      loop: "{{ apps }}"
      loop_control:
        index_var: element

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
