---
- name: Install cronjobs
  hosts: pve
  become: true
  vars:
    krawl_url: "https://krawl.carnivuth.org/{{ vault_krawl_dashboard_path }}/api/export-ips?categories=attacker,bad_crawler&fwtype=raw"
  tasks:

    - name: Install wakeup notification cronjob
      become: true
      ansible.builtin.cron:
        name: "Wakeup notification"
        special_time: reboot
        job: >
          /bin/bash -c
          'echo -e "# Wake up notification \n$(hostname) waked up at $(date)" |
          Ts.sh > /dev/null 2>&1'

    - name: Install keepalive signal
      become: true
      ansible.builtin.cron:
        name: "torterra keepalive signal"
        user: root
        minute: "*"
        hour: "*"
        job: "curl '{{ vault_healthchecks_proxmox_keepalive_signal }}' > /dev/null 2>&1"

    - name: Install updates cronjob
      become: true
      ansible.builtin.cron:
        name: "Update notification"
        user: root
        minute: "0"
        hour: "17"
        job: cd /usr/local/labcraft && make playbooks/package_status.yml > /dev/null 2>&1

    - name: Setup krawl rule syncronization
      ansible.builtin.cron:
        name: "krawl rules sync with storagebox"
        minute: "*/30"
        hour: "*"
        job: cd /usr/local/labcraft && make playbooks/krawl_ban.yml > /dev/null 2>&1
