---
- name: Install cronjobs
  hosts: pve
  become: true
  vars:
    krawl_url: "https://krawl.carnivuth.org/{{ vault_krawl_dashboard_path }}/api/export-ips?categories=attacker,bad_crawler&fwtype=raw"
  tasks:

    - name: Install updates cronjob
      become: true
      ansible.builtin.cron:
        name: "Update notification"
        user: root
        minute: "0"
        hour: "17"
        job: >
          /bin/bash -c
          'apt-get update;
          echo -e "# $HOSTNAME package status\n
          $(apt list --upgradable 2>/dev/null | grep -c '/') packages can be upgraded\n
          \n
          \`\`\`text\n
          $(apt list --upgradable 2>/dev/null)\n
          \`\`\`" | Ts.sh > /dev/null 2>&1'

    - name: Install wakeup notification cronjob
      become: true
      ansible.builtin.cron:
        name: "Wakeup notification"
        special_time: reboot
        job: >
          /bin/bash -c
          'echo -e "# Wake up notification \n$(hostname) waked up at $(date)" |
          Ts.sh > /dev/null 2>&1'

    - name: Install keepalive signal
      become: true
      ansible.builtin.cron:
        name: "torterra keepalive signal"
        user: root
        minute: "*"
        hour: "*"
        job: "curl '{{ vault_healthchecks_proxmox_keepalive_signal }}' > /dev/null 2>&1"

    - name: Install updates cronjob
      become: true
      ansible.builtin.cron:
        name: "Update notification"
        user: root
        minute: "0"
        hour: "17"
        job: >
          /bin/bash -c
          'apt-get update;
          echo -e "# $HOSTNAME package status\n
          $(apt list --upgradable 2>/dev/null | grep -c '/') packages can be upgraded\n
          \n
          \`\`\`text\n
          $(apt list --upgradable 2>/dev/null)\n
          \`\`\`" | Ts.sh > /dev/null 2>&1'

    - name: Install wakeup notification cronjob
      become: true
      ansible.builtin.cron:
        name: "Wakeup notification"
        special_time: reboot
        job: >
          /bin/bash -c
          'echo -e "# Wake up notification \n$(hostname) waked up at $(date)" |
          Ts.sh > /dev/null 2>&1'

    - name: Install keepalive signal
      become: true
      ansible.builtin.cron:
        name: "torterra keepalive signal"
        user: root
        minute: "*"
        hour: "*"
        job: "curl '{{ vault_healthchecks_proxmox_keepalive_signal }}' > /dev/null 2>&1"

    - name: Setup krawl rule syncronization
      ansible.builtin.cron:
        name: "krawl rules sync with storagebox"
        minute: "*/30"
        hour: "*"
        job: cd /usr/local/labcraft && make playbooks/ban_krawl_attackers.yml
        #job: >
        #  /bin/bash -c
        #  'curl "{{ krawl_url }}" |
        #  while read ip; do
        #  iptables -C INPUT -s  "$ip" -j DROP 2>/dev/null  ||
        #  ( iptables -I INPUT -s "$ip" -j DROP && echo "blocked ip $ip" );
        #  done |
        #  PARSE_MODE=HTML Ts.sh ' > /dev/null 2>&1
