---
- name: Setup ddclient
  become: true
  hosts: pve
  handlers:
    - name: Restart ddclient
      ansible.builtin.service:
        name: ddclient
        state: restarted
  tasks:

    - name: Install ddclient package
      ansible.builtin.apt:
        name: ddclient
        state: present
        update_cache: true

    - name: Configure ddclient
      notify: Restart ddclient
      ansible.builtin.template:
        src: "files/ddclient/ddclient.conf.j2"
        dest: "/etc/ddclient.conf"
        mode: "0600"
        owner: root

    - name: Configure dns servers to fix ddclient name resolution
      notify: Restart ddclient
      ansible.builtin.copy:
        mode: '644'
        dest: /etc/resolv.conf
        content: |
          search {{ vault_cloudflare_domain }}
          nameserver {{ vault_cloudflare_primary_dns }}
          nameserver {{ vault_cloudflare_secondary_dns }}

    - name: Get public IP address
      ansible.builtin.uri:
        url: https://ifconfig.me/ip
        return_content: true
      register: public_ip

    - name: Restart ddclient
      ansible.builtin.service:
        name: ddclient
        state: restarted

    - name: Send public ip via telegram api as debug
      community.general.telegram:
        token: "{{ vault_telegram_token }}"
        api_args:
          chat_id: "{{ vault_telegram_chat_id }}"
          parse_mode: "markdown"
          text: "proxmox public ip `{{ public_ip.content }}` "
          disable_web_page_preview: true
          disable_notification: false
