---
- name: Setup dns on dns hosts
  become: true
  hosts: dns
  tasks:

    - name: Set dns ip address
      ansible.builtin.set_fact:
        dns_ip: '{{ address | regex_replace("(.*)/.*", "\1") }}'

    - name: Copy dnsmasq configuration
      ansible.builtin.template:
        src: templates/dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        mode: '644'
      notify: Restart dnsmasq

    - name: Copy /etc/resolv.conf
      ansible.builtin.template:
        src: templates/dns.resolv.conf.j2
        dest: /etc/resolv.conf
        mode: '644'
      notify: Restart dnsmasq

    - name: Copy /etc/hosts
      ansible.builtin.template:
        src: templates/dns.hosts.j2
        dest: /etc/hosts
        mode: '644'
      notify: Restart dnsmasq

    - name: Install dnsmasq
      ansible.builtin.apt:
        name: dnsmasq
        state: present
        update_cache: true
      notify: Restart dnsmasq

  handlers:
    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
        enabled: true

- name: Set nameserver in all other nodes
  hosts: all:!dns
  become: true
  pre_tasks:
  tasks:
    - name: Setup clients dns server
      ansible.builtin.template:
        src: templates/clients.resolv.conf.j2
        dest: /etc/resolv.conf
        mode: '644'
