---
- name: Run backup job on prod nodes
  hosts: pve
  become: true
  tasks:
    - name: Backup all vms in the Proxmox cluster to storage mypbs
      community.general.proxmox_backup:
        api_user: "{{ vault_proxmox_user }}"
        api_token_id: "{{ vault_proxmox_token_id }}"
        api_token_secret: "{{ vault_proxmox_token_secret }}"
        api_host: pve
        storage: "{{ item }}"
        mode: pool
        pool: prod
      loop: "{{ groups['backupper'] }}"
