---
- name: Run backup job on prod nodes
  hosts: pve
  become: true
  tasks:
    - name: Backup all vms in the Proxmox cluster to storage mypbs
      community.general.proxmox_backup:
        api_user: "{{ vault_proxmox_user }}"
        api_token_id: "{{ vault_proxmox_token_id }}"
        api_token_secret: "{{ vault_proxmox_token_secret }}"
        api_host: pve
        storage: "{{ item }}"
        mode: pool
        compress: zstd
        retention: keep-last=10
        wait: true
        pool: prod
      loop: "{{ groups['backupper'] }}"

    - name: Notify backup job
      ansible.builtin.uri:
        url: "{{ ntfy_endpoint }}"
        method: POST
        body: "containers and vms backup has ended"
