---
- name: Install docker applications
  hosts: docker
  tasks:
    - block:
        - name: Install dependencies for docker role
          ansible.builtin.apt:
            name: gnupg
            state: present

        - name: Install docker
          ansible.builtin.include_role:
            name: geerlingguy.docker
          vars:
            docker_install_compose_plugin: false
            docker_compose_package: docker-compose-plugin
            docker_compose_package_state: present

      rescue:
        - name: Set notification message
          ansible.builtin.set_fact:
            telegram_message: |
              Failed to run task {{ ansible_failed_task.name }}  in {{ inventory_hostname }} with message:

              ```json
              {{ ansible_failed_result }}
              ```
      always:
        - name: Send Telegram notification
          community.general.telegram:
            token: "{{ vault_telegram_token }}"
            api_args:
              chat_id: "{{ vault_telegram_chat_id }}"
              parse_mode: "markdown"
              text: "{{ telegram_message | default( 'successfully run docker on ' + inventory_hostname) }}"
              disable_web_page_preview: true
              disable_notification: false
