---
- hosts: grocy_host
  tasks:
    - name: Install dependencies
      become: true
      ansible.builtin.apt:
        name:
          - nginx
          - php-common
          - php-fpm
          - php-cli
          - php8.2-gd
          - php8.2-sqlite3
          - php8.2-intl
          - php8.2-mbstring
          - sqlite3
          - unzip
        state: present
        update_cache: true

    - name: Download latest release
      ansible.builtin.get_url:
        url: 'https://releases.grocy.info/latest'
        dest: /tmp/grocy-latest.zip
        mode: '755'

    - name: Create dir
      become: true
      ansible.builtin.file:
        path: /usr/local/grocy
        state: directory
        mode: '755'

    - name: Unzip latest release
      become: true
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/grocy-latest.zip
        dest: /usr/local/grocy

    - name: Set write permissions on data dir
      become: true
      ansible.builtin.file:
        path: /usr/local/grocy/data
        mode: '755'
        owner: www-data
        state: directory
        recurse: true

    - name: add run permissions on update script
      become: true
      ansible.builtin.file:
        path: /usr/local/grocy/update.sh
        mode: +x

    - name: Copy grocy config
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: /usr/local/grocy/config-dist.php
        dest: /usr/local/grocy/data/config.php
        mode: '644'

    - name: Copy nginx config
      become: true
      ansible.builtin.copy:
        src: files/grocy
        dest: /etc/nginx/sites-available/grocy
        mode: '644'
      notify: Restart nginx

    - name: Enable nginx config
      become: true
      ansible.builtin.file:
        src: /etc/nginx/sites-available/grocy
        dest: /etc/nginx/sites-enabled/grocy
        state: link
      notify: Restart nginx

    - name: Disable nginx default config
      become: true
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart nginx

  handlers:

    - name: Restart nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
