    - name: Check for app_uid variable
      when: app_uid is undefined
      ansible.builtin.fail:
        msg: app_uid variable is not defined

    - name: Check for app variable
      when: app is undefined
      ansible.builtin.fail:
        msg: app variable is not defined

    - name: create User
      ansible.builtin.user:
        name: "{{ app }}"
        home: "{{ app_home_root }}/{{ app }}"
        uid: "{{ app_uid }}"
        create_home: true

    - name: Create directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app }}"
      loop: "{{ app_dirs }}"

    - name: Copy docker compose file
      ansible.builtin.template:
        src: "compose/{{ app }}.yml.j2"
        dest: "{{ app_home_root }}/{{ app }}/docker-compose.yml"

    - name: "Start {{ app }}"
      community.docker.docker_compose_v2:
        project_src: "{{ app_home_root }}/{{ app }}"
        state: present
        pull: always
      register: result
      retries: 5
      delay: 1

    - name: Change owner of data folder for nextcloud
      when: app == 'nextcloud'
      ansible.builtin.file:
        path: "{{ app_var_root }}/{{ app }}"
        state: directory
        owner: www-data

    - name: Send ntfy.sh update
      ansible.builtin.uri:
        url: "https://pokelab.ddns.net/ntfy/homelab"
        method: POST
        body: "{{ app }} has been provisioned"
