---
- hosts: kubernetes_control_plane,kubernetes_worker
  pre_tasks:
    - name: update packages repository
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: false
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: absent

  tasks:
    - name: Install packages for apt repo modification
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg

    - name: Add kubernetes repository key
      ansible.builtin.shell:
        cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key | gpg --dearmor --batch --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add apt repository key
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /"
        state: present
        create: true

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install kubeadm, kubelet, and kubectl
      ansible.builtin.apt:
        name:
        - kubeadm
        - kubelet
        - kubectl
        state: present

    - name: Enable cri module in containerd configuration
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: ^disabled_plugins.*
        line: '#disabled_plugins = ["cri"]'

    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted

- hosts: kubernetes_control_plane
  tasks:
    - name: Initialize Kubernetes master
      ansible.builtin.command:
        cmd: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output
      ignore_errors: true

    - name: Set up kubectl for the current user
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - "mkdir -p $HOME/.kube"
        - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
        - "chown $(id -u):$(id -g) $HOME/.kube/config"

    #- name: Install Calico network plugin
    #  ansible.builtin.command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    #  when: "'calico' in kubeadm_output.stdout"

- hosts: kubernetes-workers
  tasks:

    - name: Join worker nodes to the cluster
      when: "'kubeadm join' in hostvars['master']['kubeadm_output']['stdout']"
      ansible.builtin.command:
        cmd: "{{ hostvars['master']['kubeadm_output']['stdout_lines'][0] }}"
