---
- name: Run general configurations
  ansible.builtin.import_playbook: common.yml

- name: Configure DNS servers
  ansible.builtin.import_playbook: dns.yml

- name: Deploy docker containers
  ansible.builtin.import_playbook: service_manager.yml

- name: Provision reverse proxy server
  ansible.builtin.import_playbook: reverse_proxy.yml

- name: Configure password manager
  ansible.builtin.import_playbook: pwmanager.yml

- name: Configure backupper
  ansible.builtin.import_playbook: backupper.yml

- name: Setup vpn nodes
  ansible.builtin.import_playbook: vpn.yml
