---
- name: Create proxmox pools for resources
  hosts: localhost
  tasks:
    - name: Create pool {{ item.name }}
      community.general.proxmox_pool:
        api_host: pve
        api_user: root@pam
        api_token_id: "{{ vault_proxmox_token_id }}"
        api_token_secret: "{{ vault_proxmox_token_secret }}"
        poolid: "{{ item.name }}"
        comment: "{{ item.comment }}"
      loop: "{{ proxmox_pools }}"
