---
- name: Install nginx and certbot on reverse proxies
  hosts: reverse_proxy
  pre_tasks:
    - name: Install nginx certbot plugin
      ansible.builtin.apt:
        name: python3-certbot-nginx
        state: present

  roles:
    - role: nginxinc.nginx
      vars:
        nginx_install_from: os_repository
    - role: geerlingguy.certbot

  tasks:
    - name: remove default file
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Check for nginx site file
      ansible.builtin.stat:
        path: /etc/nginx/sites-available/main
      register: nginx_conf

    - name: Copy default configuration file
      when: not nginx_conf.stat.exists
      ansible.builtin.template:
        src: templates/main.j2
        dest: /etc/nginx/sites-available/main

    - name: enable default configuration file
      ansible.builtin.file:
        src: /etc/nginx/sites-available/main
        dest: /etc/nginx/sites-enabled/main
        state: link

    - name: Install reverse proxy for {{ apps[element].app }}
      when: apps[element].reverse_proxy is true
      ansible.builtin.include_tasks:
        file: install_nginx_conf.yml
      vars:
        app: "{{ apps[element].app }}"
        exposed_port: "{{ apps[element].exposed_port }}"
      loop: "{{ apps }}"
      loop_control:
        index_var: element

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
