- name: Setup proxmox host
  hosts: pve
  handlers:

    - name: Restart ddclient
      become: true
      ansible.builtin.service:
        name: ddclient
        state: restarted

  tasks:

    - name: Add TELEGRAM_CHAT_ID env var
      become: true
      ansible.builtin.cron:
        env: true
        name: "TELEGRAM_CHAT_ID"
        value: "{{ vault_telegram_chat_id }}"

    - name: Add TELEGRAM_TOKEN env var
      become: true
      ansible.builtin.cron:
        env: true
        name: "TELEGRAM_TOKEN"
        value: "{{ vault_telegram_token }}"

    - name: Add TELEGRAM_CHAT_ID in bashrc
      become: true
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        state: present
        line: "TELEGRAM_CHAT_ID={{ vault_telegram_chat_id }}"

    - name: Add TELEGRAM_TOKEN in bashrc
      become: true
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        state: present
        line: "TELEGRAM_TOKEN={{ vault_telegram_token }}"

    - name: Install Ts.sh script
      become: true
      ansible.builtin.copy:
        src: "setup_proxmox/Ts.sh"
        mode: "0755"
        dest: "/usr/local/bin/Ts.sh"
        owner: root
      register: ts_install

    - name: Install updates cronjob
      become: true
      ansible.builtin.cron:
        name: "Update notification"
        user: root
        minute: "0"
        hour: "17"
        job: >
          /bin/bash -c
          'apt-get update;
          echo -e "# $HOSTNAME package status\n
          $(apt list --upgradable 2>/dev/null | grep -c '/') packages can be upgraded\n
          \n
          \`\`\`text\n
          $(apt list --upgradable 2>/dev/null)\n
          \`\`\`" | Ts.sh > /dev/null 2>&1'
      register: update_cronjob

    - name: Install wakeup notification cronjob
      become: true
      ansible.builtin.cron:
        name: "Wakeup notification"
        special_time: reboot
        job: >
          /bin/bash -c
          'echo -e "# Wake up notification \n$(hostname) waked up at $(date)" |
          Ts.sh > /dev/null 2>&1'

    - name: Install keepalive signal
      become: true
      ansible.builtin.cron:
        name: "torterra keepalive signal"
        user: root
        minute: "*"
        hour: "*"
        job: "curl '{{ vault_healthchecks_proxmox_keepalive_signal }}' > /dev/null 2>&1"
      register: keepalive_cronjob

    - name: Install grafite exporter for grafana cloud
      become: true
      block:

        - name: Create directory for carbon-relay-ng
          ansible.builtin.file:
            path: "/usr/local/carbon-relay-ng/config"
            state: directory
            mode: "0755"

        - name: Install carbon-relay-ng configuration file
          ansible.builtin.template:
            src: "files/setup_proxmox/carbon-relay-ng/carbon-relay-ng.ini.j2"
            dest: "/usr/local/carbon-relay-ng/config/carbon-relay-ng.ini"
            mode: "0600"
            owner: root

        - name: Install carbon-relay-ng storage schemas configuration file
          ansible.builtin.copy:
            src: "files/setup_proxmox/carbon-relay-ng/storage-schemas.conf"
            dest: "/usr/local/carbon-relay-ng/config/storage-schemas.conf"
            mode: "0644"
            owner: root

        - name: Install carbon-relay-ng storage aggregation configuration file
          ansible.builtin.copy:
            src: "files/setup_proxmox/carbon-relay-ng/storage-aggregation.conf"
            dest: "/usr/local/carbon-relay-ng/config/storage-aggregation.conf"
            mode: "0644"
            owner: root

        - name: install docker compose file
          ansible.builtin.copy:
            src: "files/setup_proxmox/carbon-relay-ng/docker-compose.yml"
            dest: "/usr/local/carbon-relay-ng/docker-compose.yml"
            mode: "0644"
            owner: root

        - name: Start carbon-relay-ng
          community.docker.docker_compose_v2:
            project_src: "/usr/local/carbon-relay-ng"
            state: present
            pull: always
          register: result
          retries: 5
          delay: 1

    - name: Setup ddclient
      become: true
      block:

        - name: Install ddclient package
          ansible.builtin.apt:
            name: ddclient
            state: present
            update_cache: true

        - name: Configure ddclient
          notify: Restart ddclient
          ansible.builtin.template:
            src: "files/setup_proxmox/ddclient.conf.j2"
            dest: "/etc/ddclient.conf"
            mode: "0600"
            owner: root


    - name: Send Telegram notification
      community.general.telegram:
        token: "{{ vault_telegram_token }}"
        api_args:
          chat_id: "{{ vault_telegram_chat_id }}"
          parse_mode: "markdown"
          text: |
            # playbook `setup_proxmox`
            installed chronjobs on {{ inventory_hostname }}

            - update chronjob:

            ```json
            {{ update_cronjob }}
            ```

            - keepalive chronjob:

            ```json
            {{ keepalive_cronjob }}
            ```

            - ts install:

            ```json
            {{ ts_install }}
            ```

          disable_web_page_preview: true
          disable_notification: false
