- name: Setup proxmox host
  hosts: pve
  tasks:
    - name: Install updates cronjob
      become: true
      ansible.builtin.cron:
        name: "Update notification"
        user: root
        minute: "0"
        hour: "17"
        job: >
          /bin/bash -c
          'apt-get update;
          echo -e "Subject: $HOSTNAME package status\n
          $(apt list --upgradable 2>/dev/null | grep -c '/') packages can be upgraded\n
          $(apt list --upgradable 2>/dev/null)" |
          sendmail root'
      register: update_cronjob

    - name: Install keepalive signal
      become: true
      ansible.builtin.cron:
        name: "torterra keepalive signal"
        user: root
        minute: "*"
        hour: "*"
        job: "curl '{{ vault_healthchecks_proxmox_keepalive_signal }}' > /dev/null 2>&1"
      register: keepalive_cronjob

    - name: Install Ts.sh script
      become: true
      ansible.builtin.copy:
        src: "setup_proxmox/ts.sh"
        mode: "0755"
        dest: "/usr/local/bin/ts.sh"
        owner: root
      register: ts_install

    - name: Send Telegram notification
      community.general.telegram:
        token: "{{ vault_telegram_token }}"
        api_args:
          chat_id: "{{ vault_telegram_chat_id }}"
          parse_mode: "markdown"
          text: |
            # playbook `setup_proxmox`
            installed chronjobs on {{ inventory_hostname }}

            - update chronjob:

            ```json
            {{ update_cronjob }}
            ```

            - keepalive chronjob:

            ```json
            {{ keepalive_cronjob }}
            ```

            - ts install:

            ```json
            {{ ts_install }}
            ```

          disable_web_page_preview: true
          disable_notification: false
