---
- name: Run pve configuration
  hosts: pve
  roles:
    - roles/cronjobs
    - roles/graphite_exporter
    - roles/proxmox_backup_server

- name: Run global site configuration
  hosts: all
  roles:
    - roles/align_cloudflare_dns
    - roles/enforce_policies
    - roles/Ts_script
    - roles/ban_krawl_ips

- name: align all services in docker hosts
  hosts: service_manager
  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose_plugin: false
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: present
    #- roles/align_services
