---
- name: Run torterra site configuration
  hosts:
    - docker_clouds
  roles:
    - role: enforce_policies
      tags: system
    - role: cronjobs
      tags: system
    - role: Ts_script
      tags: system

    - role: align_cloudflare_dns
      tags:
        - system
        - dns

    - role: ban_krawl_ips
      tags:
        - security
        - system

    - role: geerlingguy.docker
      tags: containers
      vars:
        docker_install_compose_plugin: false
        docker_compose_package: docker-compose-plugin
        docker_compose_package_state: present
    - role: align_permissions
      tags: containers
    - role: align_services
      tags: containers
