---
- name: Setup proxmox host
  hosts: pve
  become: true
  handlers:

    - name: Restart fail2ban
      become: true
      ansible.builtin.service:
        name: fail2ban
        state: restarted

    - name: Restart sshd
      become: true
      ansible.builtin.service:
        name: sshd
        state: restarted

  tasks:

    - name: Install fail2ban package
      ansible.builtin.apt:
        name: fail2ban
        state: present
        update_cache: true
      notify: Restart fail2ban

    - name: Configure ssh daemon
      become: true
      ansible.builtin.copy:
        content: |
          Include /etc/ssh/sshd_config.d/*.conf
          StrictModes yes
          PubkeyAuthentication yes
          KbdInteractiveAuthentication no
          UsePAM yes
          X11Forwarding yes
          PrintMotd no
          AcceptEnv LANG LC_*
          Subsystem       sftp    /usr/lib/openssh/sftp-server
        dest: "/etc/ssh/sshd_config"
        mode: "0600"
        owner: root
      notify: Restart ssh
