---
- name: Configure wireguard in vpn endpoint
  become: true
  hosts: vpn
  vars:
    wireguard_postup:
      - "iptables -t nat -I POSTROUTING -s {{ wireguard_address | ansible.utils.ipaddr('network') }}/{{ wireguard_address | ansible.utils.ipaddr('prefix') }} -o eth0 -j MASQUERADE"
      - iptables -I INPUT 1 -i wg0 -j ACCEPT
      - iptables -I FORWARD 1 -i eth0 -o wg0 -j ACCEPT
      - iptables -I FORWARD 1 -i wg0 -o eth0 -j ACCEPT
      - "iptables -I INPUT 1 -i eth0 -p udp --dport {{ wireguard_port }} -j ACCEPT"

    wireguard_predown:
      - "iptables -t nat -D POSTROUTING -s {{ wireguard_address | ansible.utils.ipaddr('network') }}/{{ wireguard_address | ansible.utils.ipaddr('prefix') }} -o eth0 -j MASQUERADE"
      - iptables -D INPUT -i wg0 -j ACCEPT
      - iptables -D FORWARD -i eth0 -o wg0 -j ACCEPT
      - iptables -D FORWARD -i wg0 -o eth0 -j ACCEPT
      - "iptables -D INPUT -i eth0 -p udp --dport {{ wireguard_port }} -j ACCEPT"

  pre_tasks:
    - name: Install deps
      ansible.builtin.apt:
        name: iptables
        state: present
  roles:
    - role: githubixx.ansible_role_wireguard


