---
- name: Prepare
  hosts: all
  become: true
  pre_tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: ../../playbooks/vars/sample.yml
  tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: true

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Remove default file
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    #- name: Copy default configuration file
    #  ansible.builtin.template:
    #    src: ../../playbooks/templates/main.j2
    #    dest: /etc/nginx/sites-available/main
    #    mode: '755'

    - name: Enable default configuration file
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/main
        state: link

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
