---
services:
  krawl:
    image: ghcr.io/blessedrebus/krawl:2.0.0
    container_name: krawl
    restart: unless-stopped

    networks:
      - services

    volumes:
      - /mnt/containers/krawl/data:/app/data
      - /mnt/containers/krawl/backups:/app/backups
      - /mnt/containers/krawl/exports:/app/exports

    environment:
      - CONFIG_LOCATION=config.yaml
      - TZ=Europe/Rome
      - KRAWL_DASHBOARD_SECRET_PATH=${KRAWL_DASHBOARD_SECRET_PATH}

    labels:
      # traefik labels
      - "traefik.enable=true"
      - "traefik.http.services.krawl.loadbalancer.server.port=5000"

      # default entrypoint with authelia authentincation
      - "traefik.http.routers.krawl.entrypoints=websecure"
      - "traefik.http.routers.krawl.tls.certresolver=myresolver"
      - "traefik.http.routers.krawl.rule=Host(`${HOST}`)"

      # homepage labels
      - "homepage.group=Monitoring and access control"
      - "homepage.name=Krawl"
      - "homepage.icon=https://raw.githubusercontent.com/BlessedRebuS/Krawl/8d5ecc6a6ffd3193431dbb1b05cd3b3bc752ba52/img/krawl-svg.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=Honeypot"
networks:
  services:
    name: services
    external: true
