---
services:
  opencloud:
    container_name: opencloud
    restart: unless-stopped
    image: opencloudeu/opencloud:7.2.4
    user: ${PUID_OPENCLOUD}
    networks:
      - services
    entrypoint:
      - /bin/sh
    # run opencloud init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the opencloud server
    command: ["-c", "opencloud init || true; opencloud server"]
    env_file: .env
    environment:
      - OC_URL=https://${HOST}
        # do not use SSL between the reverse proxy and OpenCloud
      - PROXY_TLS=false
        # INSECURE: needed if OpenCloud / reverse proxy is using self generated certificates
      - OC_INSECURE=false
        # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect)
      - PROXY_ENABLE_BASIC_AUTH=false
      - OC_DEFAULT_LANGUAGE=en
      - OC_EXCLUDE_RUN_SERVICES=idp
      - PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD=jwt
      - PROXY_OIDC_REWRITE_WELLKNOWN=true
      - PROXY_AUTOPROVISION_ACCOUNTS=true
    volumes:
      # configure the .env file to use own paths instead of docker internal volumes
      - /mnt/data/opencloud/etc:/etc/opencloud
      - /mnt/data/opencloud/data:/var/lib/opencloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opencloud.rule=Host(`${HOST}`)"
      - "traefik.http.services.opencloud.loadbalancer.server.port=9200"
      - "traefik.http.routers.opencloud.entrypoints=websecure"
      - "traefik.http.routers.opencloud.tls=true"
      - "traefik.http.routers.opencloud.tls.certresolver=myresolver"

      - "homepage.group=Personal Cloud"
      - "homepage.name=Opencloud"
      - "homepage.icon=opencloud.svg"
      - "homepage.href=https://${HOST}"
      - "homepage.description=Personal fileshare"

networks:
  services:
    name: services
    external: true
